### ISSUE TITLE
ndoutils clears all entries from SQL table

### ISSUE THREAD

**Issue by rcknag** [NagiosEnterprises/ndoutils#11]
ndoutils is clearing all the entries from nagios_hosts and nagios_services table and then reinserting it again. With quite a bit of services, this takes some time.

Can it instead only update the modified changes, or new entries, rather than delete all existing data?
https://support.nagios.com/forum/viewtopic.php?f=7&t=35859

**Comment by jfrickson** [comment]
This is partially fixed with commit https://github.com/NagiosEnterprises/ndoutils/commit/ea55fd4ef019c5dae812903aa342716a7b87e55b
on branch https://github.com/NagiosEnterprises/ndoutils/tree/ndoutils-2-0

Please let me know if this speeds it up, and by how much.

**Comment by jfrickson** [comment]
This is now on branch https://github.com/NagiosEnterprises/ndoutils/tree/ndoutils-2.1b2

**Comment by jfrickson** [comment]
No comment in over a month. I'm considering this issue closed unless someone comments.
