### ISSUE TITLE
duration column in nagios_scheduleddowntime

### ISSUE THREAD

**Issue by hedenface** [NagiosEnterprises/ndoutils#12]
The duration column is represented by seconds. Currently this column is a smallint(6). A years worth of seconds is 31,536,000 - but it would be nice to schedule downtime for about 2 years - 63,072,000 seconds. In order to accommodate this, the column would need to be changed to an int(8).

**Comment by jomann09** [comment]
You forgot to mention that currently smallint(6) only allows ~ 9hr downtime duration. While this isn't going to stop anything, it's a display issue.

**Comment by jfrickson** [comment]
Changed in branch 'maint' via commit https://github.com/NagiosEnterprises/ndoutils/commit/ccce163540ab89e9217f92e84ec343debea899b2. Will be in the 2.1.2 release.
