### ISSUE TITLE
Suggestion:  Maintain KMQ ID between restarts

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/ndoutils#13]
Thoughts on having NDO maintain the ID of the kernel message queue it is using so that if it restarts it can use the old queue instead of making a new one?  Sorta like a retention.dat for NDO.  This irons out situations where there is unprocessed KMQ stuff on an unclean shutdown.

**Comment by tmcnag** [comment]
Like a squirrel burying nuts, these links might help in the future:

[ndo2db_queue_init() definition](https://github.com/NagiosEnterprises/ndoutils/blob/1ca1570a2bb78cea00e5250f789f64c7382254d7/src/queue.c#L36-L47)
[ndo2db_queue_init() called](https://github.com/NagiosEnterprises/ndoutils/blob/1ca1570a2bb78cea00e5250f789f64c7382254d7/src/ndo2db.c#L974)
[NDO_QUEUE_ID defined](https://github.com/NagiosEnterprises/ndoutils/blob/1ca1570a2bb78cea00e5250f789f64c7382254d7/include/queue.h#L26)

**Comment by hedenface** [comment]
I think this is a good idea. We'll talk about it at our next internal open source development meeting.

**Comment by hedenface** [comment]
The KMQ will be a thing of the past once NDO 3 comes out, so I'm going to close this issue.
