### ISSUE TITLE
Database creation fails in mysql.sql in fresh install

### ISSUE THREAD

**Issue by tatref** [NagiosEnterprises/ndoutils#15]
I'm using ndoutils-2.1.0

Error message:

    ** Creating tables for version 2.0.1
    Using mysql.sql for installation...
    ERRROR 1072 (42000) at line 27: Key column 'logentry_id' doesn't exit in table
    Installation from mysql.sql failed at ./installdb line 60

I think this is due to commit bc6088e, and the constraint introduced on `logentry_id`

I'm using the `installdb` script. The database is created with `grant all privileges...`.

I'm not a mysql expert, but it seems that there is no such column in `nagios_logentries`?

**Comment by jfrickson** [comment]
You are correct. A change was applied to the wrong table. Will be fixed shortly.

**Comment by jfrickson** [comment]
Fix put in on branch 'maint' (https://github.com/NagiosEnterprises/ndoutils/tree/maint) via commit https://github.com/NagiosEnterprises/ndoutils/commit/d6d2075d46cc9545f31938a8f5729e038824842c

**Comment by tatref** [comment]
Thanks a lot for the very quick fix!
