### ISSUE TITLE
addition to unique key was added to wrong table

### ISSUE THREAD

**Issue by maemigh** [NagiosEnterprises/ndoutils#16]
Line 41 of mysql.sql:

UNIQUE KEY `instance_id` (`instance_id`, `entry_time`, `entry_time_usec`, `logentry_id`)

logentry_id doesn't exist in this table. It looks like this was supposed to be added to like 838 instead.

**Comment by AnwarYagoub** [comment]
same issue with **ndoutils-2.1.1**

**Comment by qianpeng2** [comment]
I'm also meet this trouble,when I execute: `./installdb -u 'ndoutils' -p 'ndoutils_abcd' -h 'localhost' -d nagios`  ,it tells me that ERROR 1072 (42000) at line 27: Key column 'logentry_id' doesn't exist in table,and I find that there is no tables in nagios database, so,what is next ?  my NDO version is ndoutils-2.1.1.

**Comment by IonCannon23** [comment]
Having the same issue for 2.1.1, the mysql.sql has a bug for logentry_id. It is not being created.

**Comment by jfrickson** [comment]
See issue https://github.com/NagiosEnterprises/ndoutils/issues/15

This was fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/ndoutils/commit/d6d2075d46cc9545f31938a8f5729e038824842c

This fix will be in the next release (ndoutils-2.1.2) coming out soon.
