### ISSUE TITLE
Lock/PID file contains 0, instead of actual PID

### ISSUE THREAD

**Issue by tatref** [NagiosEnterprises/ndoutils#17]
Hi,

I'm using the `maint` branch, so I should be up-to-date.

I'm running into an issue on a fresh install, the PID file is created, but it always contains `0`.

Relevant lines in config file:
```
lock_file=/usr/local/nagios/var/ndo2db.pid
```

I tried to delete the file, it is recreated as expected on startup, but still contains `0`

I'm starting ndo by hand:
```
/path/to/ndo2db -c /path/to/ndo2db.cfg
```

I tested under centos 5 and 6, 64b, same behavior.

Full test:
```
git clone ...
git checkout origin/maint
cd ndoutils
./configure
make all
make install
make install-config
/usr/local/nagios/bin/ndo2db -c /usr/local/nagios/etc/ndo2db.cfg
cat /usr/local/nagios/var/ndo2db.pid           <= expecting not 0 here
```

Do you need me to provide more logs?

**Comment by jfrickson** [comment]
Fixed in branch maint via commit https://github.com/NagiosEnterprises/ndoutils/commit/2f7593ff1d4b23899a438753499232b08152b131
