### ISSUE TITLE
Is nagios_dbversion  supposed to be the current ndoutils release?

### ISSUE THREAD

**Issue by tatref** [NagiosEnterprises/ndoutils#19]
Hi,

I noticed that the table `nagios_dbversion` contains the value `2.0.1`, when the current ndoutils version is 2.1.1.

Are the versions supposed to match?

**Comment by jfrickson** [comment]
Not necessarily. 2.1.0 and 2.1.1 did not have any schema changes, so an update to `nagios_dbversion` was not required. There **will** be a minor change for 2.1.2, in which case `nagios_dbversion` will be updated.
