### ISSUE TITLE
No root group in FreeBSD and Apple OS X

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/ndoutils#22]
In FreeBSD and Apple OS X there is no "root" group, it's called "wheel".

In Makefile.in I needed to change this line:

```
INIT_OPTS=-o root -g root
```

To this:

```
INIT_OPTS=-o root -g wheel
```

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/ndoutils/commit/13cb19cdc89238c731405a8be9e53114155de168
