### ISSUE TITLE
Wrong mysql.sql

### ISSUE THREAD

**Issue by joniw** [NagiosEnterprises/ndoutils#25]
Hello,

the mysql.sql contains an error since https://github.com/NagiosEnterprises/ndoutils/commit/bc6088e0dc91f5fe01e023bf1f2e9732a6d438f9.

The file db/mysql-upgrade-2.1.0.sql contains:
"ALTER TABLE `nagios_logentries` ADD UNIQUE KEY `instance_id` (`instance_id`,`logentry_time`,`entry_time`,`entry_time_usec`,`logentry_id`);"

The file db/mysql.sql adds the unique statement for "logentry_id" to the table nagios_acknowledgements in line 27 and not to the table nagios_logentries in line 827

With regards

Jonathan

**Comment by jfrickson** [comment]
Already fixed in the 'maint' branch via commit https://github.com/NagiosEnterprises/ndoutils/commit/d6d2075d46cc9545f31938a8f5729e038824842c. Scheduled to be released on Nov 16.
