### ISSUE TITLE
Missing include in src/queue.c

### ISSUE THREAD

**Issue by orlitzky** [NagiosEnterprises/ndoutils#27]
In `queue.c`, we find the following code...

```c
void push_into_queue (char* buf) {
...
    #ifdef USE_NANOSLEEP
        delay.tv_sec = 0;
        delay.tv_nsec = 250000000;
        nanosleep(&delay,NULL);
    #else
        sleep(1);
    #endif
```

The `time.h` header for `nanosleep` is included, but `unistd.h` for `sleep` is not.

**Comment by jfrickson** [comment]
`queue.c` includes `../include/config.h` which includes `unistd.h`

**Comment by orlitzky** [comment]
Oops, I missed that. We've been carrying a patch that can be dropped, then. Thanks!
