### ISSUE TITLE
DESTDIR support removed in commit 44dbc9b

### ISSUE THREAD

**Issue by orlitzky** [NagiosEnterprises/ndoutils#28]
While attempting to upgrade the version of ndoutils shipped with Gentoo, I noticed that the support for `DESTDIR` was removed in commit 44dbc9b. The `DESTDIR` variable is an important part of autotools build systems, and we need it to be respected to build ndoutils from source. For an example of what goes wrong,

  1.  We pass `--bindir=/usr/bin` to the `./configure` script.
  2. During `make install`, the build system attempts to install directly to `/usr/bin`. That is prohibited by our sandbox, but more importantly, it changes ownership of `/usr/bin` to `nagios:nagios` and completely borks the whole system =)

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/ndoutils/commit/b69014d599628a49e8c7278eab17131604013036
