### ISSUE TITLE
Add check_options to ndoutils DB

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ndoutils#50]
Add the check_options to the host/service status data in the database. Currently it only puts in check_type and does not add the check_options value.

**Comment by sawolf** [comment]
I added this to `ndo-3`, however I'm not sure how useful it will be. 

For forced checks on the current version of Core, service status is brokered 3 times in short succession, with check_options set back to 0 for the second and third brokering. If I add a statement like `printf("Check options are %d", svc->check_options);` to the broker function, I get output like:
```
Check options are 1
Check options are 0
Check options are 0
```
I'm not sure if this is a bug in Core and/or whether this will affect other possible values of check_options.
