### ISSUE TITLE
Add port to mysql setup

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/ndoutils#55]
When upgrading or installing the database add the ability to add a custom port so that it will update properly on offloaded mysql databases.

**Comment by Madlohe** [comment]
Is this different from https://github.com/NagiosEnterprises/ndoutils/commit/476e99ea4339481f5823e7cbf18e791394f7b630 ?

**Comment by jomann09** [comment]
Yes sorry I meant the upgradedb script

**Comment by sawolf** [comment]
This is in `db-mgmt.sh` in `ndo-3`
