### ISSUE TITLE
nagios_host config data does not appear to be logging in 2.1b1

### ISSUE THREAD

**Issue by mguthrie88** [NagiosEnterprises/ndoutils#6]
I'm currently running ndoutils 2.0 and 2.1b1 side by side in our environment. Two servers are pointing their data at a remote mysql instance, and currently host config data is only populating for the 2.0 instance. I have mirrored configs in both locations, with the following ndomod.cfg options set:

object_config_data=1
config_output_options=2

So far the issue appears to be localized to just the hosts, but unfortunately for me, that's the table I need to reference for a query I'm writing. Let me know if there's any config or log data I can send along to be more specific. If need be I can setup a test instance of 2.1b1 to test any patches.

**Comment by abrist** [comment]
Hey there!  I think a handful of commits from the prep-stmts branch leaked into trunk in January.  I have the same issues with the nagios_host table on my test instances and Eric S. is aware of them (and has reproduced them).  Stick with 2.0 for now while we get this sorted.

**Comment by mguthrie88** [comment]
Ok, sounds good. Thanks guys!

**Comment by mguthrie88** [comment]
Did a fix for this ever get committed?

**Comment by jfrickson** [comment]
We're rethinking the prepared statements and will be backing them out.
Branch https://github.com/NagiosEnterprises/ndoutils/tree/ndoutils-2.1b2 is the current latest but without the prepared statements.

I'm going to close this issue, but if you still have a problem, we can reopen it.
