### ISSUE TITLE
init script update to stop head error: "cannot open /xxxx/ndo2db.lock for reading: No such file or directory"

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/ndoutils#9]
When the stop function runs, it is not uncommon to see this error message:
```
Stopping ndo2db: head: cannot open `/usr/local/nagios/var/ndo2db.lock' for reading: No such file or directory
done.
Starting ndo2db: done.
```
In the file daemon-init.in if we add 2>&1 to line 160 it stops this message:
```
if status_ndo2db > /dev/null 2>&1; then
```
Also we should do it for line 167 as well:
```
if status_ndo2db > /dev/null 2>&1; then
```

**Comment by jfrickson** [comment]
Fixed by commit https://github.com/NagiosEnterprises/ndoutils/commit/766ba542bc9dbdf36b4e65491d35f39335316883
in branch https://github.com/NagiosEnterprises/ndoutils/tree/ndoutils-2.1b2
